/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackAugustoRouteImport } from './routes/pack-augusto'
import { Route as PackLulaRouteImport } from './routes/pack-lula'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackAugustoRoute = PackAugustoRouteImport.update({
  id: '/pack-augusto',
  path: '/pack-augusto',
  getParentRoute: () => rootRouteImport,
} as any)
const PackLulaRoute = PackLulaRouteImport.update({
  id: '/pack-lula',
  path: '/pack-lula',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pack-augusto': typeof PackAugustoRoute
  '/pack-lula': typeof PackLulaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pack-augusto': typeof PackAugustoRoute
  '/pack-lula': typeof PackLulaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pack-augusto': typeof PackAugustoRoute
  '/pack-lula': typeof PackLulaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pack-augusto' | '/pack-lula'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pack-augusto' | '/pack-lula'
  id: '__root__' | '/' | '/pack-augusto' | '/pack-lula'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackAugustoRoute: typeof PackAugustoRoute
  PackLulaRoute: typeof PackLulaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-augusto': {
      id: '/pack-augusto'
      path: '/pack-augusto'
      fullPath: '/pack-augusto'
      preLoaderRoute: typeof PackAugustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-lula': {
      id: '/pack-lula'
      path: '/pack-lula'
      fullPath: '/pack-lula'
      preLoaderRoute: typeof PackLulaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackAugustoRoute: PackAugustoRoute,
  PackLulaRoute: PackLulaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
